# -*- coding: utf-8 -*-
"""Task06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FafcmA9udZ-0gUnTZSppqCN3bDvofVvC

**Task 06: Modifying RDF(s)**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2024-2025/master/Assignment4/course_materials"

"""Read the RDF file as shown in class"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/example5.rdf", format="xml")

"""Create a new class named Researcher"""

ns = Namespace("http://somewhere#")
g.add((ns.Researcher, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.1: Create a new class named "University"**

"""

ns = Namespace("http://somewhere#")
g.add((ns.University, RDF.type,RDFS.Class))
for t in g.triples((ns.University, None, None)):
  print(t)

"""**TASK 6.2: Add "Researcher" as a subclass of "Person"**"""

g.add((ns.Person, RDF.type, RDFS.Class))
g.add((ns.Researcher, RDFS.subClassOf, ns.Person))
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.3: Create a new individual of Researcher named "Jane Smithers"**"""

researcher_nombre = Literal("Jane Smithers")
g.add((ns.Jane_Smithers,RDF.type,ns.Researcher))
g.add((ns.Jane_smithers,RDFS.label,researcher_nombre))
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.4: Add to the individual JaneSmithers the email address, fullName, given and family names. Use the https://schema.org vocabulary**"""

SCHEMA = Namespace("https://www.google.com/url?q=https%3A%2F%2Fschema.org")
vcard = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
g.add((ns.Jane_Smithers,SCHEMA.email, Literal("Jane_smithers@gmail.com")))
g.add((ns.Jane_Smithers,SCHEMA.givenName, Literal("Jane")))
g.add((ns.Jane_Smithers,SCHEMA.adress, Literal("seventy_steet")))
g.add((ns.Jane_Smithers,SCHEMA.familyName, Literal("Smithers")))
g.add((ns.Jane_Smithers,vcard.FN, Literal("Jane Smithers")))
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.5: Add UPM as the university where John Smith works. Use the "https://example.org/ namespace**"""

Ex = Namespace("https://www.google.com/url?q=https%3A%2F%2Fexample.org%2F")
g.add((Ex.UPM, RDF.type, ns.University))
g.add((ns.JohnSmith,SCHEMA.worksfor,Ex.UPM))
for s, p, o in g:
  print(s,p,o)

"""**Task 6.6: Add that Jown knows Jane using the FOAF vocabulary. Make sure the relationship exists.**"""

from rdflib.namespace import FOAF
g.namespace_manager.bind('foaf', FOAF)
g.add((ns.JohnSmith, FOAF.knows, ns.Jane_Smithers))
for s, p, o in g:
  print(s,p,o)