# -*- coding: utf-8 -*-
"""Task08.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cVj_F06bK8jpsWsd56welU4u5jE2Q9dq

**Task 08: Completing missing data**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2024-2025/master/Assignment4/course_materials"

from rdflib import Graph, Namespace, Literal, URIRef
from rdflib.namespace import RDF
g1 = Graph()
g2 = Graph()
g1.parse(github_storage+"/rdf/data01.rdf", format="xml")
g2.parse(github_storage+"/rdf/data02.rdf", format="xml")

ns = Namespace("http://somewhere/")
vcard = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")

for person in g1.subjects(RDF.type, ns.Person):
    given_name = g1.value(person, vcard.givenName)
    family_name = g1.value(person, vcard.familyName)
    email = g1.value(person, vcard.email)
    if not given_name:
        given_name = g2.value(person, vcard.givenName)
        if given_name:
            print(f"Nombre encontrado en g2: {given_name}")
    if not family_name:
        family_name = g2.value(person, vcard.familyName)
        if family_name:
            print(f"Apellido encontrado en g2: {family_name}")
    if not email:
        email = g2.value(person, vcard.email)
        if email:
            print(f"Email encontrado en g2: {email}")

    print(f"Persona: {person}")
    print(f"  Nombre: {given_name}")
    print(f"  Apellido: {family_name}")
    print(f"  Email: {email}")
    print("\n")

"""Tarea: lista todos los elementos de la clase Person en el primer grafo (data01.rdf) y completa los campos (given name, family name y email) que puedan faltar con los datos del segundo grafo (data02.rdf). Puedes usar consultas SPARQL o iterar el grafo, o ambas cosas."""