  SELECT ?station ?code ?name ?latitude ?longitude
  WHERE {
    ?station a ns:Estación ;
             ns:codigoEstacion ?code ;
             ns:nombreEstacion ?name ;
             geo:lat ?latitude ;
             geo:long ?longitude .
  }

  SELECT ?nucleo ?nucleoName ?station
  WHERE {
      ?nucleo a ns:NucleoCercanias ;
      ns:nombreNucleo ?nucleoName .
      ?station ns:tieneNucleo ?nucleo .
  }


  SELECT ?station ?stationName ?address ?addressName
  WHERE {
    ?station a ns:Estación ;
             ns:nombreEstacion ?stationName ;
             ns:localizadoEn ?address .
    ?address ns:nombreDireccion ?addressName .
  }


  SELECT ?provincia ?poblacion
  WHERE {
    ?provincia a ns:Provincia .
    ?poblacion a ns:Poblacion .
    ?provincia ns:tienePoblacion ?poblacion .
  }


  SELECT ?segment ?interval ?station ?subidos ?bajados
  WHERE {
    ?segment a ns:Tramo ;
    ns:intervalo ?interval ;
    ns:tieneEstacion ?station ;
    ns:viajerosSubidos ?subidos ;
    ns:viajerosBajados ?bajados .
  } LIMIT 10


  