# -*- coding: utf-8 -*-
"""Task06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RS5ZbTuurigW09xNomcjeZOWkaiQF-WK

**Task 06: Modifying RDF(s)**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2024-2025/master/Assignment4/course_materials"

"""Read the RDF file as shown in class"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/example5.rdf", format="xml")

"""Create a new class named Researcher"""

ns = Namespace("http://somewhere#")
g.add((ns.Researcher, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.1: Create a new class named "University"**

"""

ns_1 = Namespace('http://somewhere#')
g.add((ns_1.University, RDF.type, RDFS.Class))
# Visualize the results
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.2: Add "Researcher" as a subclass of "Person"**"""

g.add((ns_1.Person, RDF.type, RDFS.Class))
g.add((ns_1.Researcher, RDFS.subClassOf, ns.Person))
# Visualize the results
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.3: Create a new individual of Researcher named "Jane Smithers"**"""

name = Literal('Jane Smithers')
uri_Jane = ns_1.JaneSmithers
g.add((uri_Jane, RDF.type, ns_1.Researcher))
# Visualize the results
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.4: Add to the individual JaneSmithers the email address, fullName, given and family names. Use the https://schema.org vocabulary**"""

sch = Namespace("https://schema.org/")
g.namespace_manager.bind('sch', Namespace("https://schema.org/"), override=False)
g.add((ns.JaneSmithers, sch.email, Literal("jsimthers@smwhere.com")))
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.5: Add UPM as the university where John Smith works. Use the "https://example.org/ namespace**"""

UPM = Literal('UPM')
EX =  Namespace("https://example.org/")
ns_2 = Namespace('http://somewhere#')
UriUPM = EX.UPM
g.add((UriUPM, RDF.type, ns_1.University))
g.add((ns_2.JohnSmith, EX.works, UriUPM))
for s,p,o in g:
  print(s,p,o)

"""**Task 6.6: Add that Jown knows Jane using the FOAF vocabulary. Make sure the relationship exists.**"""

from rdflib.namespace import FOAF
g.add((ns.JohnSmith, FOAF.knows, ns.Jane_Smithers))
for s, p, o in g:
  print(s,p,o)