# -*- coding: utf-8 -*-
"""Task06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qteVfqXQzNiTZtU630mYQXnV5IinB8rk

**Task 06: Modifying RDF(s)**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2024-2025/master/Assignment4/course_materials"

"""Read the RDF file as shown in class"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/example5.rdf", format="xml")

"""Create a new class named Researcher"""

ns = Namespace("http://somewhere#")
g.add((ns.Researcher, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.1: Create a new class named "University"**

"""

# TO DO
# Visualize the results
g.add((ns.University, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.2: Add "Researcher" as a subclass of "Person"**"""

# TO DO
# Visualize the results
g.add((ns.Researcher, RDFS.subClassOf, ns.Person))
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.3: Create a new individual of Researcher named "Jane Smithers"**"""

# TO DO
# Visualize the results
from rdflib.namespace import FOAF
g.add((ns.jane_smithers, RDF.type, ns.Researcher))
g.add((ns.jane_smithers, FOAF.name, Literal("Jane Smithers")))
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.4: Add to the individual JaneSmithers the email address, fullName, given and family names. Use the https://schema.org vocabulary**"""

# TO DO
# Visualize the results
schema = Namespace("https://schema.org/")

g.namespace_manager.bind('schema', schema)

g.add((ns.jane_smithers, schema.name, Literal("Jane Smithers")))
g.add((ns.jane_smithers, schema.givenName, Literal("Jane")))
g.add((ns.jane_smithers, schema.familyName, Literal("Smithers")))
g.add((ns.jane_smithers, schema.email, Literal("jane.smithers@example.com")))

for s, p, o in g:
  print(s,p,o)

"""**TASK 6.5: Add UPM as the university where John Smith works. Use the "https://example.org/ namespace**"""

# TO DO
# Visualize the results

example = Namespace("https://example.org/")
g.namespace_manager.bind('ex', example)
g.add((example.upm, RDF.type, schema.Organization))
g.add((example.upm, schema.name, Literal("Universidad Politécnica de Madrid")))
g.add((ns.john_smith, schema.worksFor, example.upm))

for s, p, o in g:
  print(s,p,o)

"""**Task 6.6: Add that Jown knows Jane using the FOAF vocabulary. Make sure the relationship exists.**"""

# TO DO
# Visualize the results
g.add((ns.john_smith, FOAF.knows, ns.jane_smithers))

for s, p, o in g:
  print(s,p,o)